spring.application.name=apiMarketplace
spring.datasource.url=jdbc:postgresql://localhost:5432/api_marketplace
spring.datasource.username=postgres
spring.datasource.password=henrique1408

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true